title: Laura Payan Cepeda
logo: logo: ![image](VIVI-202 (5).jpg){: width="50px" height="50px" }
#description: Passionate about turning data into strategy
#show_downloads: true
theme: jekyll-theme-minimal
