title: Laura Payan Cepeda
logo: logo: ![image](VIVI-202 (5).jpg){: width="150px" height="150px" }
#description: Passionate about turning data into strategy
#show_downloads: true
theme: jekyll-theme-minimal
